name: PlayerBuff23
version: "${version}"
main: net.azisaba.playerbuff23.PlayerBuff23
api-version: "1.15"
authors: [Azisaba Network]

commands:
  playerbuff:
    description: PlayerBuff23 main command
    permission: playerbuff.command.main
  playerbuffset:
    description: PlayerBuff set command
    aliases:
      - pbset
      - pbs
    permission: playerbuff.command.set

permissions:
  playerbuff.command.*:
    description: Permission to use PlayerBuff23 commands
    children:
      playerbuff.command.main: true
      playerbuff.command.set: true
      playerbuff.command.reload: true
      playerbuff.command.pbs: true
    default: op
  playerbuff.command.main:
    description: Permission to use PlayerBuff23 main command
    default: op
  playerbuff.command.set:
    description: Permission to set PlayerBuff23
    default: op
  playerbuff.command.reload:
    description: Permission to reload configuration via /playerbuff
    default: op
  playerbuff.command.pbs:
    description: Permission to use /pbs command
    default: op
